spring.datasource.url=jdbc:postgresql://localhost:5432/Market
spring.datasource.username=postgres
spring.datasource.password=06031995DH
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.change-log=classpath:db/changelog/changelog-master.yaml